name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    
    # 添加 MSVC 环境变量设置
    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Build
      run: |
        mkdir build
        cd build
        qmake ../QtFrameLessWindow.pro
        nmake
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QtFrameLessWindow-windows
        path: build/release/
