name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # 检出代码
    - name: Checkout
      uses: actions/checkout@v2
    
    # 安装 Visual Studio
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    # 安装 Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    
    # 创建构建目录
    - name: Create Build Directory
      run: mkdir build
    
    # 运行 qmake 和构建
    - name: Build
      run: |
        cd build
        qmake ../QtFrameLessWindow.pro
        nmake
    
    # 运行 windeployqt（可选）
    - name: Deploy Qt
      run: |
        cd build/release
        windeployqt QtFrameLessWindow.exe
    
    # 上传构建结果（可选）
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: QtFrameLessWindow-windows
        path: build/release/
